### ISSUE TITLE
Radio button groups and items: support for `accessibleName` and `helpText`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#899]
Related to Related to https://github.com/phetsims/models-of-the-hydrogen-atom/issues/67 and https://github.com/phetsims/sun/issues/901 ...

The first problem is with the group:

Radio button groups (RectangularRadioButtonGroup, AquaRadioButtonGroup) are examples of where sim-specific code is using low-level PDOM APIs.   For example, in greenhouse-effect, see inner class ConcentrationControlModeRadioButtonGroup in GreenhouseGasConcentrationPanel.ts:

```ts
        // pdom
        labelTagName: 'h4',
        labelContent: GreenhouseEffectStrings.a11y.concentrationPanel.experimentModeStringProperty,
        helpText: GreenhouseEffectStrings.a11y.concentrationPanel.experimentModeHelpTextStringProperty,
```

This is not what is desired in sim-specific code. `labelContent` should not be part of the API, it should be `accessibleName`.  Then the implementation of the radio button group (common code) should propagate `accessibleName` to `labelContent`, if that's what is important. 

Setting specific headings, like `labelTagName: 'h4'` is also concerning, because it depending on knowledge of where this instance appears in the PDOM, and knowledge that play area and control area are `'h2'`.  I'll create a separate issue about this, but it would be preferrable if this could be somehow added automatically based on where the component is added to the PDOM.

The second problem is with radio button group items, for example RectangularRadioButtonGroupItem:

```ts
export type RectangularRadioButtonGroupItem<T> = {
  ...
  labelContent?: PDOMValueType; // optional label for a11y (description and voicing)
  voicingContextResponse?: VoicingResponse;
  descriptionContent?: PDOMValueType; // optional label for a11y
  options?: StrictOmit<RectangularRadioButtonOptions, 'tandem'>; // options passed to RectangularRadioButton constructor
} & GroupItemOptions;
```

All of these description-related options are identified as low-level, and should not be used in sim code.  They are also redundant because they can be passed through `RectangularRadioButtonGroupItem.options`.  For example:

```ts
const item: RectangularRadioButtonGroupItem<...> = {
    value: ...,
    createNode: ...,
    options: {
      voicingContextResponse: 'voicing context response',
      descriptionContent: 'description content',
      accessibleName: 'accessible name',
      helpText: 'help text'
    },
};
```

So the API for RectangularRadioButtonGroupItem and other group items needs to be revisited.

**Comment by jessegreenberg** [comment]
For the first part of the problem, that is a general issue that we will solve in other common code components in #900 and possibly https://github.com/phetsims/scenery/issues/855.

For the second part of the problem, in the above commits I removed the accessibility related items from `AquaRadioButtonGroupItem` and `RectangularRadioButtonGroupItem` so that they are passed through options. I updated sim usages and ran local aqua and spot checked quadrilateral, greenhouse-effect, friction, ratio-and-proportion, and gravity-force-lab-basics.

Finally, I fixed a bug with the default `accessibleNameBehavior` so that `accessibleName` sets the `labelContent` correctly: https://github.com/phetsims/scenery/issues/1670, for these TODOs: 
>//TODO description: https://github.com/phetsims/sun/issues/899 Should be using accessibleName instead of labelContent.

@pixelzoom is that all for this issue and can it be closed?

**Comment by pixelzoom** [comment]
@jessegreenberg I still see these in MOTHA.  Did something not get pushed? 

And should it still possible be possible to use `labelContent` with radio button groups, or should that option (and others?) be excluded?

**Comment by jessegreenberg** [comment]
Ah, sorry, I have been leaving the TODOs in. It is ready to change from `labelContent` to `accessibelName`. And `labelContent` should also be disallowed, probably with https://github.com/phetsims/scenery/issues/1666.

**Comment by pixelzoom** [comment]
OK, I pushed the updates to MOTHA.  If disallowing options is to be handled elsewhere, feel free to close this issue.

**Comment by jessegreenberg** [comment]
OK, I used `TrimParallelDOMOptions` for radio button groups and radio buttons in https://github.com/phetsims/sun/commit/5ceb2479748e0d0d3d250b2918295498ea15f6d8 and https://github.com/phetsims/sun/commit/8b2575f00e9c9a20deb3273db6a6de951e54a557. 

This can now be closed.
